//Local Host
GET http://localhost:8080/contacts

GET http://localhost:8080/contacts/65ac62eda241d28ebf0eb62d

GET http://localhost:8080/contacts/65ac62f7a241d28ebf0eb62f

GET http://localhost:8080/contacts/65ac6302a241d28ebf0eb631